CREATE TRIGGER TR_DIRECCIONES ON Direcciones
INSTEAD OF INSERT
AS
BEGIN
	BEGIN TRY
		BEGIN TRANSACTION
			DECLARE @ID INT
			DECLARE @DIRECCION VARCHAR(100)
			DECLARE @NUMERO INT
			DECLARE @DEPARTAMENTO VARCHAR(100)
			DECLARE @CIUDAD VARCHAR(100)
			DECLARE @PROVINCIA VARCHAR(100)
			DECLARE @PAIS VARCHAR(100)

			
			--REGISTRO DIRECCIONES PERSONAS, ACCEDO A LOS DATOS
	
			SELECT @ID = ID, @DIRECCION = DIRECCION, @NUMERO = NUMERO, @DEPARTAMENTO = DEPARTAMENTO, @CIUDAD = CIUDAD, @PROVINCIA = PROVINCIA, @PAIS = PAIS FROM INSERTED
			
			INSERT INTO [ALBORNOZ_DB].[dbo].[Direcciones]([id],[direccion],[numero],[departamento],[ciudad],[provincia],[pais]) 
			VALUES(@ID, @DIRECCION, @NUMERO, @DEPARTAMENTO, @CIUDAD, @PROVINCIA, @PAIS)
	COMMIT TRANSACTION
	END TRY
	BEGIN CATCH
		ROLLBACK TRANSACTION
	END CATCH
END
