CREATE TRIGGER TR_ALTA ON Clientes
INSTEAD OF INSERT
AS
BEGIN
	BEGIN TRY
		BEGIN TRANSACTION
			DECLARE @IDPERSONA INT
			DECLARE @ID INT	
			DECLARE @NOMBRE VARCHAR(100)
			DECLARE @APELLIDO VARCHAR(100)
			DECLARE @DNI INT
			DECLARE @DIRECCION VARCHAR(100)
			DECLARE @NUMERO INT
			DECLARE @DEPARTAMENTO VARCHAR(100)
			DECLARE @CIUDAD VARCHAR(100)
			DECLARE @PROVINCIA VARCHAR(100)
			DECLARE @PAIS VARCHAR(100)
			DECLARE @EMAIL VARCHAR(100)
			DECLARE @TELEFONO INT
			
			--REGISTRO CLIENTE, ACCEDO A LOS DATOS A INSERTAR
			INSERT INTO [ALBORNOZ_DB].[dbo].[Personas]([nombre],[apellido],[dni_cuit],[imagen])VALUES(@NOMBRE,@APELLIDO,@DNI,@IMAGEN)
			GO
			SELECT @ID = ID, @IDPERSONA = (SELECT TOP(1) id FROM Personas ORDER BY id DESC), @FECHANACIMIENTO = FECHANACIMIENTO, @FECHAREGISTRO = FECHAREGISTRO FROM INSERTED
			GO
			INSERT INTO [ALBORNOZ_DB].[dbo].[Clientes]([idPersona],[fechaNacimiento],[fechaRegistro])
			VALUES(@IDPERSONA,@FECHANACIMIENTO,GETDATE())
	
			INSERT INTO [ALBORNOZ_DB].[dbo].[Direcciones]([id],[direccion],[numero],[departamento],[ciudad],[provincia],[pais])
			VALUES(@ID,@DIRECCION,@NUMERO,@DEPARTAMENTO,@CIUDAD,@PROVINCIA,@PAIS)
			GO
			INSERT INTO [ALBORNOZ_DB].[dbo].[Emails]([id],[email])
			VALUES(@ID,@EMAIL)
			GO
			INSERT INTO [ALBORNOZ_DB].[dbo].[Telefonos]([id],[tipo],[numero])
			VALUES((Select top(1) id from Personas order by id desc),'Personal',1560180043)
			GO
			INSERT INTO [ALBORNOZ_DB].[dbo].[Clientes]([idPersona],[fechaNacimiento],[fechaRegistro])
			VALUES((Select top(1) id from Personas order by id desc),'09-04-1994',GETDATE())
	COMMIT TRANSACTION
	END TRY
	BEGIN CATCH
		ROLLBACK TRANSACTION
	END CATCH
END




