
CREATE TRIGGER TR_ALTA ON Personas
INSTEAD OF INSERT
AS
BEGIN
	BEGIN TRY
		BEGIN TRANSACTION	
			DECLARE @NOMBRE VARCHAR(50)
			DECLARE @APELLIDO VARCHAR(50)
			DECLARE @IMAGEN VARCHAR(500)
			DECLARE @DNI_CUIT INT
			DECLARE @ID INT

			--REGISTRO CLIENTE, ACCEDO A LOS DATOS A INSERTAR
			SELECT @ID = ID, @NOMBRE = NOMBRE, @APELLIDO = APELLIDO, @DNI_CUIT = DNI_CUIT, @IMAGEN = IMAGEN FROM INSERTED
			--INSERTA REGISTRO
			INSERT INTO [ALBORNOZ_DB].[dbo].[Personas]([nombre],[apellido],[dni_cuit],[imagen])VALUES(@NOMBRE,@APELLIDO,@DNI_CUIT,@IMAGEN)
			
	COMMIT TRANSACTION
	END TRY
	BEGIN CATCH
		ROLLBACK TRANSACTION
	END CATCH
END
