CREATE TRIGGER TR_Email ON Emails
INSTEAD OF INSERT
AS
BEGIN
	BEGIN TRY
		BEGIN TRANSACTION

			DECLARE @ID INT	
			DECLARE @EMAIL VARCHAR(100)
			
			--REGISTRO CLIENTE, ACCEDO A LOS DATOS A INSERTAR
	
			SELECT @ID = ID , @EMAIL = EMAIL FROM INSERTED
			
			INSERT INTO [ALBORNOZ_DB].[dbo].[Emails]([id],[email])
			VALUES(@ID,@EMAIL)
			
	COMMIT TRANSACTION
	END TRY
	BEGIN CATCH
		ROLLBACK TRANSACTION
	END CATCH
END
